In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('PlayTennis.csv')

In [3]:
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

Yeh batana hai khela jaayega ki nhi 

It is a basic classification problem can be solved it using simple logistic regression

In [31]:
# P(yes)
# P(no)

df['Play Tennis'].value_counts()

Play Tennis
Yes    9
No     5
Name: count, dtype: int64

In [32]:
py = 9/14
pn = 5/14

In [35]:
#outlook

pd.crosstab(df['Outlook'] , df['Play Tennis'])

Play Tennis  No  Yes
Outlook
Overcast      0    4
Rain          2    3
Sunny         3    2

In [ ]:
# NO use of writing that i thought